services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    env_file:
      - docker.env
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer:${ADMINER_VERSION:-4.8.1}
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always

volumes:
  database_data:
